var searchData=
[
  ['uart16550_5fregs_5f_5479',['uart16550_regs_',['../structuart16550__regs__.html',1,'']]],
  ['uart_5fbuf_5480',['uart_buf',['../structuart__buf.html',1,'']]],
  ['uart_5fsoftc_5481',['uart_softc',['../structuart__softc.html',1,'']]],
  ['upsample_5ft_5482',['upsample_t',['../upsamplers_8h.html#structupsample__t',1,'']]],
  ['usb_5fmmio_5fhwport_5f_5483',['usb_mmio_hwport_',['../iop__mmio__hwport_8h.html#structusb__mmio__hwport__',1,'']]],
  ['usbconfigdescriptor_5484',['UsbConfigDescriptor',['../usbd_8h.html#struct_usb_config_descriptor',1,'']]],
  ['usbdevicedescriptor_5485',['UsbDeviceDescriptor',['../usbd_8h.html#struct_usb_device_descriptor',1,'']]],
  ['usbdevicerequest_5486',['UsbDeviceRequest',['../usbd_8h.html#struct_usb_device_request',1,'']]],
  ['usbendpointdescriptor_5487',['UsbEndpointDescriptor',['../usbd_8h.html#struct_usb_endpoint_descriptor',1,'']]],
  ['usbhubdescriptor_5488',['UsbHubDescriptor',['../usbd_8h.html#struct_usb_hub_descriptor',1,'']]],
  ['usbinterfacedescriptor_5489',['UsbInterfaceDescriptor',['../usbd_8h.html#struct_usb_interface_descriptor',1,'']]],
  ['usbm_5fload_5fentry_5490',['usbm_load_entry',['../structusbm__load__entry.html',1,'']]],
  ['usbmass_5fcmd_5491',['usbmass_cmd',['../structusbmass__cmd.html',1,'']]],
  ['usbmassdeviceinfo_5492',['UsbMassDeviceInfo',['../usbhdfsd_8h.html#struct_usb_mass_device_info',1,'']]],
  ['usbstringdescriptor_5493',['UsbStringDescriptor',['../usbd_8h.html#struct_usb_string_descriptor',1,'']]],
  ['utimbuf_5494',['utimbuf',['../structutimbuf.html',1,'']]]
];
